In [3]:
import pandas as pd
import os

In [8]:
os.getcwd()

'/Users/danielschene/MakeAIWork/practica/week3'

In [37]:
df = pd.read_csv('energie_afhankelijkheid.csv', sep=';', encoding='latin1')

In [38]:
display(df)

,country,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,C.A. de Euskadi,"94,25488685","94,1780926","94,50532908","93,99908887","93,31378488","93,1527524","92,91494738","92,48458875","90,00062012","89,97489898","89,75796178","88,95525218"
1,UE 27,"55,766","56,359","54,918","53,939","54,421","56,064","56,16","57,548","58,138","60,481","57,459","55,595"
2,Alemania,"59,992","61,801","61,215","62,411","61,779","62,132","63,752","63,959","63,478","67,055","63,676","63,885"
3,Austria,"62,779","69,976","63,782","61,261","65,62","60,371","62,099","63,928","64,221","71,597","58,415","51,96"
4,Belgica,"78,553","76,464","76,563","77,777","80,102","84,145","75,891","75,257","82,968","77,592","78,043","70,817"
5,Bulgaria,"40,146","36,732","36,859","38,313","35,171","36,446","38,472","39,362","36,325","38,109","37,884","36,137"
6,Chipre,"100,636","92,263","96,748","96,071","93,086","97,319","95,841","95,927","92,491","92,792","93,179","89,524"
7,Croacia,"46,693","49,639","49,862","47,434","44,206","48,786","48,43","53,156","52,695","56,216","53,564","54,536"
8,Dinamarca,"-16,235","-6,315","-3,176","12,312","12,225","13,077","13,568","11,343","22,733","38,718","45,065","32,562"
9,Eslovaquia,"64,448","65,933","61,625","60,825","62,135","60,102","60,551","64,845","63,679","69,762","56,329","52,584"
10,Eslovenia,"49,277","48,329","51,813","47,461","45,187","49,304","49,017","50,769","51,213","52,116","45,68","48,615"
11,Espa√±a,"77,003","76,012","72,798","69,997","72,557","72,741","71,486","73,886","73,613","75,034","67,892","69,094"
12,Estonia,"14,68","13,646","20,647","14,522","11,562","11,181","8,069","4,584","1,208","4,725","10,525","1,412"
13,Finlandia,"48,859","53,914","47,109","49,662","49,935","47,946","46,161","43,939","45,341","43,017","43,191","38,011"
14,Francia,"48,668","49,049","48,199","48,013","46,239","45,929","47,394","48,793","46,84","47,548","44,402","44,111"
15,Grecia,"68,584","64,677","65,889","61,75","65,455","71,047","72,911","71,282","70,681","74,103","81,415","73,819"
16,Hungria,"56,93","50,273","50,146","50,122","59,845","53,875","55,823","62,645","58,123","69,712","56,618","54,11"
17,Irlanda,"87,484","90,352","83,71","91,624","86,15","88,777","69,082","66,87","67,556","68,631","71,153","76,963"
18,Italia,"82,571","81,353","79,109","76,736","75,811","77,03","77,653","76,979","76,338","77,484","73,454","73,537"
19,Letonia,"45,545","59,863","56,388","55,883","40,592","51,179","47,152","44,053","44,313","43,913","45,481","38,333"
20,Lituania,"79,045","78,604","77,534","75,556","74,935","75,452","74,784","71,965","73,897","75,202","74,909","73,272"
21,Luxemburgo,"97,069","97,293","97,51","97,1","96,626","95,958","96,28","95,558","95,153","95,006","92,331","92,468"
22,Malta,"99,036","101,3","100,973","104,139","97,657","97,296","101,076","103,052","97,527","97,274","97,555","97,058"
23,Pa√≠ses Bajos,"28,279","29,357","30,635","23,738","30,948","48,998","45,909","51,788","59,435","64,36","68,021","58,379"
24,Polonia,"31,569","34,02","31,628","26,254","29,415","29,848","30,76","38,269","43,505","45,237","42,76","40,443"
25,Portugal,"75,22","77,792","79,461","73,347","70,234","76,293","72,241","77,965","75,657","73,875","65,282","66,925"
26,Republica Checa,"25,379","28,831","25,413","27,58","30,227","32,089","32,8","37,162","36,879","40,807","38,763","39,996"
27,Ruman√≠a,"21,386","21,14","22,463","18,317","16,663","16,687","21,901","23,295","24,291","30,282","28,191","31,645"
28,Suecia,"37,99","36,476","30,164","32,79","32,335","30,061","33,301","26,658","29,059","30,044","31,98","21,217"